# Generated by Django 5.2.13 on 2026-06-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(choices=[('LOR', 'lor'), ('THERAPIST', 'therapist'), ('SURGEON', 'surgeon'), ('DENTIST', 'dentist'), ('CARDIOLOGIST', 'cardiologist')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('Doctor', 'Doctor'), ('Patient', 'Patient')], default='Patient', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
