# Generated by Django 5.2.13 on 2026-06-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('telephone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('times', models.IntegerField()),
            ],
        ),
    ]
