# Generated by Django 5.2.13 on 2026-06-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='message',
            field=models.TextField(default='asdasdad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('Accept', 'accept'), ('Refuse', 'refuse')], default='Accept', max_length=11),
            preserve_default=False,
        ),
    ]
