# Generated by Django 5.2.13 on 2026-06-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('profession', models.CharField(choices=[('LOR', 'LOR'), ('THERAPIST', 'Therapist'), ('SURGEON', 'Surgeon'), ('DENTIST', 'Dentist'), ('CARDIOLOGIST', 'Cardiologist')], max_length=100)),
            ],
        ),
    ]
