# Generated by Django 6.0.6 on 2026-07-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('therapist', 'Терапевт'), ('cardiologist', 'Кардиолог'), ('surgeon', 'Хирург'), ('pediatrician', 'Педиатр'), ('dermatologist', 'Дерматолог'), ('neurologist', 'Невролог'), ('gynecologist', 'Гинеколог'), ('ophthalmologist', 'Офтальмолог'), ('dentist', 'Стоматолог'), ('orthopedist', 'Ортопед')], default='therapist', max_length=30),
        ),
    ]
